spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: dev
  jade4j:
    caching: false
    prettyPrint: true
server:
  port: 9000
logging:
  level:
    todoapp: DEBUG
app:
  asset-host: localhost:8080

---
spring:
  profiles: production
endpoints:
  enabled: false
  health.enabled: true
app:
  asset-host: ts-ng-webpack.5ik.biz
