spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/customers;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
  jade4j:
    caching: false
    prettyPrint: true
server:
  port: 9000
logging:
  level:
    todoapp: DEBUG
app:
  asset-host: localhost:8080

---
spring:
  profiles: heroku
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  jade4j:
    caching: true
    prettyPrint: false
app:
  asset-host: ts-ng-webpack.5ik.biz
